// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDetailsList(arg1, arg2) {
  return window['go']['controllers']['Binlog']['GetDetailsList'](arg1, arg2);
}

export function GetTitleList(arg1) {
  return window['go']['controllers']['Binlog']['GetTitleList'](arg1);
}
