// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';
import {orm} from '../models';

export function GetDetailsList(arg1:number,arg2:controllers.SearchBinlog):Promise<controllers.DetailsList>;

export function GetTitleList(arg1:number):Promise<Array<orm.UploadLogs>>;
