// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDecodeRowCount():Promise<number>;

export function GetSystemFile():Promise<string>;

export function GetTitleList():Promise<Array<string>>;
