// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllData() {
  return window['go']['controllers']['Files']['ClearAllData']();
}

export function DeleteFile(arg1) {
  return window['go']['controllers']['Files']['DeleteFile'](arg1);
}

export function GetDecodeRowCount() {
  return window['go']['controllers']['Files']['GetDecodeRowCount']();
}

export function GetSystemFile() {
  return window['go']['controllers']['Files']['GetSystemFile']();
}

export function GetTitleList(arg1, arg2) {
  return window['go']['controllers']['Files']['GetTitleList'](arg1, arg2);
}

export function SaveToSqlite(arg1) {
  return window['go']['controllers']['Files']['SaveToSqlite'](arg1);
}
