// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDecodeRowCount() {
  return window['go']['controllers']['Files']['GetDecodeRowCount']();
}

export function GetSystemFile() {
  return window['go']['controllers']['Files']['GetSystemFile']();
}

export function GetTitleList() {
  return window['go']['controllers']['Files']['GetTitleList']();
}
