// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controllers} from '../models';

export function ClearAllData():Promise<void>;

export function DeleteFile(arg1:number):Promise<void>;

export function GetDecodeRowCount():Promise<number>;

export function GetSystemFile():Promise<string>;

export function GetTitleList(arg1:number,arg2:number):Promise<controllers.TitleData>;

export function SaveToSqlite(arg1:string):Promise<string>;
