// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exit() {
  return window['go']['controllers']['Help']['Exit']();
}

export function OpenURL(arg1) {
  return window['go']['controllers']['Help']['OpenURL'](arg1);
}
